# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20220317.0.0"
  config.vm.network "private_network", ip: "192.168.11.22"
  config.vm.synced_folder "www/", "/var/www/html", create: true
  config.vm.provider "virtualbox"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get install apache2 -y
  echo 'ServerName localhost' >> /etc/apache2/apache2.conf
  sudo service apache2 restart
SHELL
end
